version: 5.3.4.{build}

image: Visual Studio 2017

skip_commits:
  files:
    - .travis.yml

branches:
  except:
  - linux
  - /.lin./
  - /.travis./

environment:
  LUA_VERSION: "5.3.4"
  SRC_DIR: "lua\\lua-$LUA_VERSION"
  TEST_DIR: "lua\\lua-$LUA_VERSION-tests"
  SCRIPTS_DIR: "win"
  BUILD_DIR: "build"
  LUA_X64_DEBUG_BINDIR: ".\\lua\\x64\\Debug\\"
  LUA_X64_RELEASE_BINDIR: ".\\lua\\x64\\Release\\"
  LUA_X86_DEBUG_BINDIR: ".\\lua\\x86\\Debug\\"
  LUA_X86_RELEASE_BINDIR: ".\\lua\\x86\\Release\\"

init:
  - git config --global core.autocrlf input

build_script:
  - ps: Push-Location -Path msbuild
  - ps: Get-Location
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - msbuild /property:Platform=x64 /property:Configuration=Debug /verbosity:normal
  - msbuild /property:Platform=x64 /property:Configuration=Release /verbosity:normal
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - msbuild /property:Platform=x86 /property:Configuration=Debug /verbosity:normal
  - msbuild /property:Platform=x86 /property:Configuration=Release /verbosity:normal
  - ps: Write-Host "Successfully build lua-$env:LUA_VERSION"
  - ps: Pop-Location
  - ps: Get-Location

before_test:
  - ps: Push-Location -Path $env:BUILD_DIR
  - ps: Push-Location -Path $env:LUA_X64_RELEASE_BINDIR
  - ps: Get-Location
  - ps: ls
  - ps: .\lua.exe -v
  - ps: Pop-Location
  - ps: Push-Location -Path $env:LUA_X64_DEBUG_BINDIR
  - ps: Get-Location
  - ps: ls
  - ps: .\lua.exe -v
  - ps: Pop-Location
  - ps: Push-Location -Path $env:LUA_X86_DEBUG_BINDIR
  - ps: Get-Location
  - ps: ls
  - ps: .\lua.exe -v
  - ps: Pop-Location
  - ps: Push-Location -Path $env:LUA_X86_RELEASE_BINDIR
  - ps: Get-Location
  - ps: ls
  - ps: .\lua.exe -v
  - ps: Pop-Location
  - ps: Pop-Location
  - ps: Write-Host "Simple interpreter version echoing test done..."
  - ps: Get-Location
  - ps: Write-Host "section 'before_test' done"

test_script:
  - ps: .\$env:SCRIPTS_DIR\Makefile.ps1 install
  # We need to source as the install script does not effect the current
  # PowerShell session
  - ps: Get-Content -Path C:\Lua\luaprofile.ps1
  - ps: . C:\Lua\luaprofile.ps1
  - ps: Write-Host $env:Path
  - ps: lua.exe -v
  - ps: Write-Host "Successfully installed lua-$env:LUA_VERSION"
  # We successfully build and installed, now lets get to testing
  - ps: powershell .\$env:SCRIPTS_DIR\generate-test-directories.ps1
  - ps: Write-Host "Starting tests"
  - ps: Write-Host 'Runnig simple test -e"_U=true"'
  # We run the tests in cmd instead of PowerShell, since PowerShell on AppVeyor
  # thinks there is an error, but in fact if testing locally there is none.
  - cmd: lua.exe -e"_U=true" all_win.lua
  - ps: Write-Host 'Simple test successful'
  - ps: Write-Host "Running full tests"
  - ps: Push-Location -Path $env:APPVEYOR_BUILD_FOLDER
  - ps: powershell .\$env:SCRIPTS_DIR\single-script-test.ps1
  - ps: Write-Host "Done testing"
  # Now we set the build up to compile with ltests, therefore we first copy the
  # sources and then we patch the msbuild files
  - ps: powershell .\$env:SCRIPTS_DIR\ltests-update-sources.ps1
  # - ps: git apply .\$env:SCRIPTS_DIR\ltests-vcxproj.patch
