version: 5.3.4.{build}

image:
  - Visual Studio 2017
  - Ubuntu

init:
  - git config --global core.autocrlf input

install:
  - ps: |
      if ($isWindows) {
        $rmpath = "Docker", "SQL", "Mercurial", "Subversion", "Maven", "CMake", "nodejs", "nunit", "nuget", "java", "xunit", "go", "python", "Amazon", "ruby", "perl", "Azur", "Webdriver", "Coverity", "Octopus", "erl9", "LLVM", "dotnet", "iojs", "curl", "Yarn", "chocolatey", "npm"
        Write-Host "Original `$env:Path"
        Write-Host ($env:Path).Replace(';',"`n")
        foreach ($i in $rmpath) {
          $env:path = ($env:path -split ";").Where({!($_ -like "*$i*")}) -join ";"
        }
        Write-Host "New `$env:Path"
        Write-Host ($env:Path).Replace(';',"`n")
      }
  - cmd: C:\Miniconda37-x64\Scripts\activate
  - cmd: conda install pylint flake8 vs2017_win-64 -c anaconda -y -q
  - cmd: deactivate

before_build:
  # ensure that only well formated wscripts are checked in
  - cmd: C:\Miniconda37-x64\Scripts\activate
  - cmd: flake8
  - cmd: pylint wscript
  - cmd: pylint lua\wscript
  - cmd: deactivate

build_script:
  # Windows gcc
  - cmd: C:\Miniconda37-x64\Scripts\activate
  - cmd: python waf configure --check-c-compiler=gcc build install
  - cmd: python waf build
  - cmd: python waf install
  - cmd: python waf uninstall
  - cmd: python waf distclean
  - cmd: deactivate
  # Windows x64 msvc
  - cmd: C:\Miniconda37-x64\Scripts\activate
  - cmd: python waf configure
  - cmd: python waf build
  - cmd: python waf install
  - cmd: python waf uninstall
  - cmd: python waf distclean
  - cmd: deactivate
  # Linux gcc
  - sh: python waf configure
  - sh: python waf build
  - sh: python waf install
  - sh: python waf uninstall
  - sh: python waf distclean
