version: 5.3.4.{build}

image: Visual Studio 2017

skip_commits:
  files:
    - .travis.yml

branches:
  except:
  - linux
  - /.lin./
  - /.travis./

environment:
  LUA_VERSION: "5.3.4"

init:
  - git config --global core.autocrlf input

build_script:
  - ps: Set-Location -Path lua
  - ps: Push-Location -Path lua-$env:LUA_VERSION
  - ps: Get-Location
  # - msbuild TODO
  - ps: Write-Host "Successfully build lua-$env:LUA_VERSION"
  # install script TODO
  - ps: Write-Host "Successfully installed lua-$env:LUA_VERSION"
  - ps: Get-Command lua
  - lua -v
  - ps: Pop-Location
  - $env:TESTS="lua-$env:LUA_VERSION-tests"
  - ps: Set-Location -Path $env:TESTS
  - ps: Set-Location -Path libs
  - ps: New-Item -ItemType directory -Path P1
  - ps: Set-Location -Path ..
  - ps: Write-Host "Starting tests"
  #- sudo lua all.lua TODO
  - ps: Write-Host "Done testing"
  - ps: exit 1
