env:
  global:
    - LUA_VERSION=5.3.4

compiler:
  - gcc

branches:
  except:
  - msbuild
  - /.win./

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

script:
  - cd lua
  - pushd lua-$LUA_VERSION
  - echo "$PWD"
  - make linux
  - echo "Successfully build lua-$LUA_VERSION"
  - sudo make install
  - echo "Successfully installed lua-$LUA_VERSION"
  - which lua
  - lua -v
  - popd
  - TESTS=lua-$LUA_VERSION-tests
  - cd $TESTS
  - cd libs
  - mkdir P1
  - cd ..
  - echo "Starting tests"
  - sudo lua all.lua
  - echo "Done testing"
