env:
  global:
    - LUA_VERSION=5.3.4

compiler:
  - gcc

branches:
  except:
  - msbuild
  - /.win./

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

script:
  # Build lua WITHOUT ltests and install it and run tests with -e"_U=true" and
  # without.
  # After testing this, we clean and uninstall
  - pushd lua
  - pushd lua-$LUA_VERSION
  - echo "$PWD"
  - make linux
  - echo "Successfully build lua-$LUA_VERSION"
  - sudo make install
  - echo "Successfully installed lua-$LUA_VERSION"
  - which lua
  - lua -v
  - popd
  - pushd $TRAVIS_BUILD_DIR
  - pwd & sudo linux/generate-test-directories.sh
  - popd
  - popd
  - pwd
  # We successfully build and installed, now lets get to testing
  - pushd lua/lua-$LUA_VERSION-tests
  - echo "Starting tests"
  - echo "Runnig simple test -e\"_U=true\""
  - sudo lua -e"_U=true" all.lua
  - echo "Running full tests without testC"
  - sudo lua all.lua
  - popd
  # After testing went good, we need to prepare for a clean build
  - pushd lua/lua-$LUA_VERSION
  - make clean
  - sudo make uninstall
  # Now we set the build up to compile with ltests, therefore we first copy the
  # sources and then we patch the Makefile
  - linux/ltests-update-sources.sh
  - pushd $TRAVIS_BUILD_DIR
  - git apply linux/ltests-Makefile.patch
  - popd
  - while read line; do echo "$line"; done < ./src/Makefile
  - make linux
  - echo "Successfully build lua-$LUA_VERSION with testC"
  - sudo make install
  - popd
  - cd $TESTS
  - echo "Runnig simple test -e\"_U=true\" with testC"
  - sudo lua -e"_U=true" all.lua
  - echo "Running full tests with testC"
  - sudo lua all.lua
  - cd ..
  - echo "Done testing"
