env:
  global:
    - LUA_VERSION=5.3.4

compiler:
  - gcc

branches:
  except:
  - msbuild
  - /.win./

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

script:
  - cd lua
  - pushd lua-$LUA_VERSION
  - echo "$PWD"
  - make linux
  - echo "Successfully build lua-$LUA_VERSION"
  - sudo make install
  - echo "Successfully installed lua-$LUA_VERSION"
  - which lua
  - lua -v
  - popd
  - TESTS=lua-$LUA_VERSION-tests
  - cd $TESTS
  - cd libs
  - mkdir P1
  - make
  - cd ..
  - echo "Starting tests"
  - echo "Runnig simple test -e\"_U=true\""
  - sudo lua -e"_U=true" all.lua
  - echo "Running full tests without testC"
  - sudo lua all.lua
  - cd ..
  - pushd lua-$LUA_VERSION
  - make clean
  - cp ../$TESTS/ltests/* ./src
  - sed -i "s/CFLAGS= -O2 -Wall -Wextra/CFLAGS= -O2 -Wall -Wextra -DLUA_USER_H=ltests.h/" ./src/Makefile
  - sed -i 's/ltests.h/"ltests.h"/' ./src/Makefile
  - make linux
  - sudo make install
  - popd
  - cd $TESTS
  - sudo lua all.lua
  - cd ..
  - echo "Done testing"
