language: python
sudo: required
dist: xenial
python: "3.7"
os: linux

script:
  - python3.7 waf configure --include-tests
  # gcc [
  - python3.7 waf build_gcc
  - python3.7 waf install_gcc
  - pushd build/gcc/lua/lua-5.3.4-tests
  - lua -e"_U=true" all.lua
  - lua all.lua
  - popd
  - python3.7 waf uninstall_gcc
  - python3.7 waf clean_gcc
  # gcc ]
  # clang [
  - python3.7 waf build_clang
  - python3.7 waf install_clang
  - pushd build/clang/lua/lua-5.3.4-tests
  - lua -e"_U=true" all.lua
  - lua all.lua
  - popd
  - python3.7 waf uninstall_clang
  - python3.7 waf clean_clang
  # clang ]
  - python3.7 waf distclean
  # including ltests
  - python3.7 waf configure --ltests --include-tests
  # gcc [
  - python3.7 waf build_gcc
  - python3.7 waf install_gcc
  - pushd build/gcc/lua/lua-5.3.4-tests
  - lua -e"_U=true" all.lua
  - lua all.lua
  - popd
  - python3.7 waf uninstall_gcc
  - python3.7 waf clean_gcc
  # gcc ]
  # clang [
  - python3.7 waf build_clang
  - python3.7 waf install_clang
  - pushd build/clang/lua/lua-5.3.4-tests
  - lua -e"_U=true" all.lua
  - lua all.lua
  - popd
  - python3.7 waf uninstall_clang
  - python3.7 waf clean_clang
  # clang ]
  - python3.7 waf distclean
  # Linux ]
