env:
  global:
    - LUA_VERSION=5.3.4
    - SRC_DIR=lua/lua-$LUA_VERSION
    - TEST_DIR=lua/lua-$LUA_VERSION-tests
    - SCRIPTS_DIR=linux

compiler:
  - gcc

branches:
  except:
  - msbuild
  - /.win./

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

script:
  # Build lua WITHOUT ltests and install it and run tests with -e"_U=true" and
  # without.
  # After testing this, we clean and uninstall
  - pushd $SRC_DIR
  - make linux
  - echo "Successfully build lua-$LUA_VERSION"
  - sudo make install
  - echo "Successfully installed lua-$LUA_VERSION"
  - which lua
  - lua -v
  - popd
  # We successfully build and installed, now lets get to testing
  - bash $SCRIPTS_DIR/generate-test-directories.sh
  - pushd $TEST_DIR
  - echo "Starting tests"
  - echo "Runnig simple test -e\"_U=true\""
  - sudo lua -e"_U=true" all.lua
  - echo "Simple test successful"
  - echo "Running full tests without testC"
  - sudo lua all.lua
  - echo "Normal test successful"
  - echo "Done testing"
  - popd
  # After testing went good, we need to prepare for a clean build
  - pushd $SRC_DIR
  - make clean
  - sudo make uninstall
  - popd
  # Now we set the build up to compile with ltests, therefore we first copy the
  # sources and then we patch the Makefile
  - bash $SCRIPTS_DIR/ltests-update-sources.sh
  - git apply $SCRIPTS_DIR/ltests-Makefile.patch
  - pushd $SRC_DIR
  - make linux
  - echo "Successfully build lua-$LUA_VERSION with testC"
  - sudo make install
  - popd
  - pushd $TEST_DIR
  - echo "Runnig simple test -e\"_U=true\" with testC"
  - sudo lua -e"_U=true" all.lua
  - echo "Running full tests with testC"
  - sudo lua all.lua
  - echo "Done testing"
